# Docs for the Azure Web Apps Deploy action: https://github.com/Azure/webapps-deploy
# More GitHub Actions for Azure: https://github.com/Azure/actions

name: Build and deploy container app to Azure Web App - aletheia-spring

on:
  push:
    branches:
      - main
  workflow_dispatch:

jobs:
  build:
    runs-on: 'ubuntu-latest'

    steps:
    - uses: actions/checkout@v2

    - name: Set up Docker Buildx
      uses: docker/setup-buildx-action@v2

    - name: Log in to registry
      uses: docker/login-action@v2
      with:
        registry: https://index.docker.io/v1/
        username: ${{ secrets.AzureAppService_ContainerUsername_e4c29217fea1409196528f61b35ac935 }}
        password: ${{ secrets.AzureAppService_ContainerPassword_ee9b0aaf86bb4ee3b8bfcc1c3f9d86e6 }}

    - name: Build and push container image to registry
      uses: docker/build-push-action@v3
      with:
        push: true
        tags: index.docker.io/${{ secrets.AzureAppService_ContainerUsername_e4c29217fea1409196528f61b35ac935 }}/sonosapatinho/aletheia-springboot:${{ github.sha }}
        file: ./Dockerfile

  deploy:
    runs-on: ubuntu-latest
    needs: build
    environment:
      name: 'production'
      url: ${{ steps.deploy-to-webapp.outputs.webapp-url }}

    steps:
    - name: Deploy to Azure Web App
      id: deploy-to-webapp
      uses: azure/webapps-deploy@v2
      with:
        app-name: 'aletheia-spring'
        slot-name: 'production'
        publish-profile: ${{ secrets.AzureAppService_PublishProfile_e05e626223b24f7fa5e5eb7601c93cdb }}
        images: 'index.docker.io/${{ secrets.AzureAppService_ContainerUsername_e4c29217fea1409196528f61b35ac935 }}/sonosapatinho/aletheia-springboot:${{ github.sha }}'