name: Java CI with Maven (mult-projects)

on:
  push:
    branches: [ "main" ]
  pull_request:
    branches: [ "main" ]

jobs:
  build:
    runs-on: ubuntu-latest

    strategy:
      matrix:
        projeto: [Aletheia-monolito, microservice]

    steps:
      - name: Checkout do código
        uses: actions/checkout@v4

      - name: Configurar JDK 21
        uses: actions/setup-java@v4
        with:
          java-version: '21'
          distribution: 'temurin'
          cache: maven

      - name: Build e testes do ${{ matrix.projeto }}
        working-directory: ${{ matrix.projeto }}
        run: mvn clean verify
